"""Pytest configuration for meeting_app vibeval tests.

[Generated by VibeCoding] This conftest:
1. Loads vibeval datasets
2. Provides a fixture that creates tracked mock wrappers
3. Saves vibeval-format results after each test
"""

import json
import time
from pathlib import Path
from typing import Any
from unittest.mock import patch

import pytest
import yaml


# --- vibeval dataset loading ---

FEATURE_DIR = Path(__file__).parent.parent  # tests/vibeval/meeting_summary/
DATASETS_DIR = FEATURE_DIR / "datasets"
RESULTS_DIR = FEATURE_DIR / "results"


def load_dataset(name: str) -> dict[str, Any]:
    """Load a dataset manifest + items."""
    ds_dir = DATASETS_DIR / name
    manifest = yaml.safe_load((ds_dir / "manifest.yaml").read_text())

    items = {}
    for f in sorted(ds_dir.iterdir()):
        if f.name.startswith("manifest"):
            continue
        if f.suffix == ".json":
            data = json.loads(f.read_text())
            item_id = data.pop("_id", f.stem)
            items[item_id] = data

    return {"manifest": manifest, "items": items}


MEETING_DS = load_dataset("meeting_summaries")


@pytest.fixture(params=list(MEETING_DS["items"].keys()))
def meeting_item(request):
    """Parametrized fixture: yields each dataset item."""
    item_id = request.param
    return item_id, MEETING_DS["items"][item_id]


# --- vibeval result saving ---

class VibevalResultCollector:
    """Collects turn-based trace and saves vibeval-format results (v0.2)."""

    def __init__(self, test_name: str, dataset: str, item_id: str, item_data: dict):
        self.test_name = test_name
        self.dataset = dataset
        self.item_id = item_id
        self.item_data = item_data
        self.turns: list[dict] = []
        self.outputs: dict = {}
        self.start_time = time.time()
        # Current turn being built
        self._current_input: dict = {}
        self._current_steps: list[dict] = []

    def begin_turn(self, input_data: dict):
        """Start a new turn with the given input."""
        self._current_input = input_data
        self._current_steps = []

    def step(self, step_type: str, data: dict):
        """Record a processing step in the current turn."""
        self._current_steps.append({
            "type": step_type,
            "data": data,
            "timestamp": time.time(),
        })

    def end_turn(self, output_data: dict):
        """Complete the current turn with the given output."""
        self.turns.append({
            "turn": len(self.turns) + 1,
            "input": self._current_input,
            "steps": self._current_steps,
            "output": output_data,
        })

    def save(self, run_id: str = "latest"):
        duration = time.time() - self.start_time
        result = {
            "test_name": self.test_name,
            "dataset": self.dataset,
            "item_id": self.item_id,
            "judge_results": [],
            "trace": {"turns": self.turns},
            "inputs": {k: v for k, v in self.item_data.items() if not k.startswith("expected")},
            "outputs": self.outputs,
            "timestamp": self.start_time,
            "duration": duration,
        }

        run_dir = RESULTS_DIR / run_id
        run_dir.mkdir(parents=True, exist_ok=True)
        path = run_dir / f"{self.test_name}__{self.item_id}.result.json"
        path.write_text(json.dumps(result, indent=2, default=str, ensure_ascii=False))
        return path
