"""vibeval tests for the meeting summarizer pipeline (v0.2 turn-based trace).

[Generated by VibeCoding] — single-turn test, each run is 1 turn:
  input (meeting transcript) → steps (fetch + llm×2) → output (summary)
"""

from unittest.mock import patch

from meeting_app.summarizer import summarize_meeting
from .conftest import VibevalResultCollector, MEETING_DS


MOCK_LLM_RESPONSES = {
    "standup": [
        "Meeting summary: The standup at 9:00 AM covered several topics. "
        "Bob completed the API refactoring (due March 15th) and will handle "
        "the database migration before the 3:00 PM deployment. Charlie has a "
        "client meeting at 2:30 PM about Q2 roadmap (deadline April 1st) and "
        "will review Bob's PR before 11:00 AM. All-hands at 4:00 PM. "
        "Meeting ended at 9:15 AM.",
        "- [Bob] Complete database migration before 3:00 PM deployment\n"
        "- [Charlie] Review Bob's PR before 11:00 AM\n"
        "- [Charlie] Client meeting at 2:30 PM re: Q2 roadmap\n"
        "- [All] Attend all-hands at 4:00 PM",
    ],
    "planning": [
        "Project planning meeting between Diana and Eve. "
        "Phase 1 deadline: June 30th (kickoff was January 15th). "
        "Mid-project review: April 15th at 10:00 AM. "
        "Weekly syncs: every Tuesday at 3:30 PM. "
        "Final demo: July 5th. Report due: July 10th. "
        "Next sprint planning: Monday at 9:30 AM.",
        "- [Diana] Ensure Phase 1 completion by June 30th\n"
        "- [Eve] Set up sprint planning for Monday at 9:30 AM\n"
        "- [Eve] Prepare for mid-project review on April 15th at 10:00 AM\n"
        "- [Diana] Prepare final demo for July 5th\n"
        "- [Diana] Submit report by July 10th",
    ],
}


class TestMeetingSummarizer:

    def test_summarize(self, meeting_item):
        item_id, item_data = meeting_item

        collector = VibevalResultCollector(
            test_name="test_summarize",
            dataset="meeting_summaries",
            item_id=item_id,
            item_data=item_data,
        )

        # Single turn: input is the meeting request
        collector.begin_turn({
            "content": f"Summarize meeting {item_data['meeting_id']}",
            "meeting_id": item_data["meeting_id"],
            "speakers": item_data["speakers"],
        })

        # Tracked mocks that record steps
        llm_responses = iter(MOCK_LLM_RESPONSES[item_id])

        def tracked_llm(prompt, system=""):
            collector.step("llm_call", {
                "prompt_preview": prompt[:200],
                "system": system,
            })
            response = next(llm_responses)
            collector.step("llm_output", {
                "content_preview": response[:200],
            })
            return response

        def tracked_api(meeting_id):
            transcript = {
                "meeting_id": meeting_id,
                "speakers": item_data["speakers"],
                "text": item_data["text"],
                "duration_minutes": item_data.get("duration_minutes", 0),
            }
            collector.step("tool_call", {
                "name": "fetch_transcript",
                "args": {"meeting_id": meeting_id},
            })
            collector.step("tool_result", {
                "name": "fetch_transcript",
                "result": {"speakers": transcript["speakers"], "text_length": len(transcript["text"])},
            })
            return transcript

        # Run pipeline
        with patch("meeting_app.llm_client.chat", side_effect=tracked_llm):
            with patch("meeting_app.transcript_api.fetch_transcript", side_effect=tracked_api):
                result = summarize_meeting(item_data["meeting_id"])

        # Complete the turn
        collector.end_turn({
            "content": result["summary"],
            "summary": result["summary"],
            "action_items": result["action_items"],
            "speakers": result["speakers"],
        })

        collector.outputs = {
            "summary": result["summary"],
            "action_items": result["action_items"],
            "speakers": result["speakers"],
            "meeting_id": result["meeting_id"],
        }

        collector.save(run_id="latest")
